#!/bin/bash

set -u
set -e
set -o pipefail
set -x

# if the build directory already exists, do nothing
[ -d build ] && exit 0

# create the relevant directories
mkdir build
pushd build

mkdir debug
mkdir release

# create the debug build tree
pushd debug
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../stage ../../src $@
popd

# create the release build tree
pushd release
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../../stage ../../src $@
popd

# done
popd

