def build(context):
    context(
        source = [
            "__init__.py",
            "actions.py",
            "alchemy.py",
            ],
        install_path = "${PYTHONDIR}/cargo/sql",
        )

    context.recurse("test")

