def build(context):
    context(
        source = [
            "__init__.py",
            "test_io.py",
            "test_iterators.py",
            "test_json.py",
            "test_numpy.py",
            "test_random.py",
            "test_sugar.py",
            "test_temporal.py",
            ],
        install_path = "${PREFIX}/lib/cargo/test",
        )

