def build(context):
    context(
        source = [
            "__init__.py",
            "accounting.py",
            "proc.py",
            "sessions.py",
            ],
        install_path = "${PREFIX}/lib/cargo/unix",
        )

