def build(context):
    context(
        source = [
            "__init__.py",
            "triggered.py",
            ],
        install_path = "${PYTHONDIR}/cargo/tools",
        )

    context.recurse("labor")
    context.recurse("sql")

